CodeChecker/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeChecker.Controllers
{
    [Authorize("CanUseAdminPanel")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CodeChecker/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeChecker.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CodeChecker/Controllers/FaqController.cs
using CodeChecker.Models.Models;
using CodeChecker.Models.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CodeChecker.Controllers
{
    public class FaqController : BaseController
    {


        public FaqController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CodeChecker/Controllers/GymController.cs
using CodeChecker.Models.Models;
using CodeChecker.Models.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CodeChecker.Controllers
{
    public class GymController : BaseController
    {
        private readonly ContestRepository _contestRepo;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationUserRepository _userRepo;

        public GymController(ContestRepository contestRepo, UserManager<ApplicationUser> userManager, ApplicationUserRepository userRepo)
        {
            _contestRepo = contestRepo;
            _userManager = userManager;
            _userRepo = userRepo;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CodeChecker/Views/Shared/Partials/_Footer.cshtml
<section id="footer">
    <div class="logo v-align">
        <a href="/">
            <img src="assets/logo-text.png" alt="Sity logo"/>
        </a>
    </div>
    <div class="text v-align">
        <strong>Arvydas Daubaris</strong> && <strong>Erlandas Trumpcikas</strong> &copy; @DateTime.Now.Year
    </div>
</section>

CodeChecker/Views/Shared/Partials/_Navbar.cshtml
<section id="header" ng-app="app-navbar">
    <div class="clearfix">
        <div class="logo pull-left">
            <a href="/">
                <img src="assets/logo-smaller.png" alt="SITY Logo"/>
            </a>
        </div>
        <div class="pull-right">
            @if (!User.Identity.IsAuthenticated)
            {
                <ul class="top-menu">
                    <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                    <li><a href="@Url.Action("Register", "Account")">Register</a></li>
                </ul>

            }
            else
            {
                <ul class="top-menu">
                    <li>Welcome, <span class="text-hover-underline">@User.Identity.Name</span>!</li>
                    <div ng-controller="navbarController">
                        <!-- Single button using append-to-body -->
                        <div class="btn-group" uib-dropdown dropdown-append-to-body>
                            <button id="btn-append-to-body" type="button" class="btn btn-primary" uib-dropdown-toggle>Control Panel<span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" uib-dropdown-menu role="menu" aria-labelledby="btn-append-to-body">
                                <li role="menuitem"><a class="dropdown-item" href="@Url.Action("Index", "Profile")"><i class="fa fa-user"></i> Profile</a></li>
                                @if (ViewContext.HttpContext.User.IsInRole("Administrator") || ViewContext.HttpContext.User.IsInRole("Moderator") || ViewContext.HttpContext.User.IsInRole("Contributor"))
                                {
                                    <li role="menuitem"><a class="dropdown-item" href="@Url.Action("Index", "Admin")"><i class="fa fa-file"></i> Admin panel</a></li>
                                }
                                <li role="menuitem"><a class="dropdown-item" href="@Url.Action("Logout", "Account")"><i class="fa fa-lock"></i> Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </ul>
            }
        </div>
    </div>
</section>



<div class="col-12">
<div class="row">
    <section id="menu">
        <ul>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Home") ? "active" : "")">
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Contest") ? "active" : "")">
                <a class="" href="@Url.Action("Index", "Contest")">Contests</a>
            </li>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Gym") ? "active" : "")">
                <a href="@Url.Action("Index", "Gym")">Gym</a>
            </li>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Submission") ? "active" : "")">
                <a href="@Url.Action("Index", "Submission")">Submissions</a>
            </li>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Faq") ? "active" : "")">
                <a href="@Url.Action("Index", "Faq")">Faq</a>
            </li>
            <li class="@(Url.RouteUrl(ViewContext.RouteData.Values) == Url.Action("Index", "Contact") ? "active" : "")">
                <a href="@Url.Action("Index", "Contact")">Contact Us</a>
            </li>
        </ul>
    </section>
</div>
</div>